[package]
name = "blackbox"
version = "0.1.0"
authors = ["Niels Janssen <niels@appliedcreative.nl>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_tracing = "0.2.1"

[build-dependencies]
bindgen = "0.69.4"
